### PR TITLE
Force loopback pinentry-mode

### PR DESCRIPTION
**Pull request by websecnl**
Fixes an issue with GPG:

gpg: signing failed: Inappropriate ioctl for device
gpg: [stdin]: clear-sign failed: Inappropriate ioctl for device

### CODE REVIEW

**Comment by oh2fih** [comment]
This is not a general issue with GnuPG that affects everyone. The error is probably caused by a gpg-agent misconfiguration. Furthermore, the suggested patch will override the default settings, disabling the user to choose the desired pinentry mode.

> `--pinentry-mode mode` - -
> 
> - `loopback`
>    Redirect Pinentry queries to the caller. Note that in contrast to Pinentry the user is not prompted again if he enters a bad password.

Not prompting the password again seems hardly a generally desired behavior.

**Comment by oh2fih** [comment]
The root cause for `Inappropriate ioctl for device` is that GnuPG doesn't know where to read the input from. Try:

```
export GPG_TTY=$(tty)
```

A proper solution for this with the behavior you suggest would be:

 - In `~/.gnupg/gpg.conf`, add:
    ```
    use-agent 
    pinentry-mode loopback
    ```
- in `~/.gnupg/gpg-agent.conf`, add:
   ```
   allow-loopback-pinentry
   ```

**Closing as non-issue, cannot reproduce & unwanted change.**

**Comment by websecnl** [comment]
Alright :) Well, still good to have this in the history here so other users know.
I had to figure this out the hard way.

**Comment by oh2fih** [comment]
:+1: I agree that this is good for documentation. Could have been opened as an issue, too.

:sunglasses: It is also always cool to see someone is using my work.

**Pull request closed without merging**
